# CSIT 359/553 Homework 1
## [Shibbir Ahmed Arif]:

In [ ]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import warnings
warnings.simplefilter("ignore")

In [ ]:
import numpy as np
import pandas as pd

## About the dataset: Immigration to Canada from 1980 to 2013
Dataset Source: International migration flows to and from selected countries - The 2015 revision.
https://www.un.org/en/development/desa/population/migration/data/empirical2/migrationflows.asp

The dataset contains annual data on the flows of international migrants as recorded by the countries of destination. The data presents both inflows and outflows according to the place of birth, citizenship or place of previous / next residence both for foreigners and nationals. The current version presents data available from 45 countries.

In this assignment, we focus on the Canadian immigration data.

## Question 1 ( 5 pts)

Load the file **Canada.xlsx** as a dataframe named **df** in Pandas using **read_excel**. Skip first 20 rows and last 2 rows from the excel file.

Hint:
**read_excel** is similar to **read_csv**. You could find the details of parameters setting from the following link:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/Dataset/Canada.xlsx", skiprows=20, skipfooter=2)
df

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Immigrants,Foreigners,Viet Nam,935,Asia,920,South-Eastern Asia,902,Developing regions,1191,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Immigrants,Foreigners,Western Sahara,903,Africa,912,Northern Africa,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
192,Immigrants,Foreigners,Yemen,935,Asia,922,Western Asia,902,Developing regions,1,...,124,161,140,122,133,128,211,160,174,217
193,Immigrants,Foreigners,Zambia,903,Africa,910,Eastern Africa,902,Developing regions,11,...,56,91,77,71,64,60,102,69,46,59
194,Immigrants,Foreigners,Zimbabwe,903,Africa,910,Eastern Africa,902,Developing regions,72,...,1450,615,454,663,611,508,494,434,437,407

## Question 2  ( 5 pts)
Drop the first two columns (Type and Coverage) from **df**.

In [ ]:
df1 = df.drop(columns=['Type', 'Coverage'])
df1.head()

,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,1981,1982,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,39,39,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,67,71,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,1,0,...,0,0,1,0,0,0,0,0,0,0
4,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,0,0,...,0,0,1,1,0,0,0,0,1,1

## Question 3  ( 10 pts)
Write a function named **max_name** that, given a value of **AreaName** and a year between 1980 and 2013, returns the origin (value in **OdName**) with the maximum immigrants.

In [ ]:
def max_name(place, year):

    place_df = df[df['AreaName'] == place]

    year_column = int(year)

    max_row = place_df[year_column].idxmax()

    country_name = place_df.loc[max_row, 'OdName']

    return country_name

print("Country with the maximum immigrants:")
print(max_name('Asia', 2013))
print(max_name('Asia', 1980))
print(max_name('Europe', 2000))

Country with the maximum immigrants:
China
India
United Kingdom of Great Britain and Northern Ireland

In [ ]:
# sample code to test your answer
# max_name ('Asia', 2013), max_name ('Asia', 1980), max_name ('Europe', 2000)
# output:
# ('China', 'India', 'United Kingdom of Great Britain and Northern Ireland')

## Question 4  ( 15 pts)
Write a function named **max_year** that, given one parameter of origin ( value in **OdName**), returns the year with the maximum immigrants.

In [35]:
def max_immigrant_year(origin):

    selected_data = df[df['OdName'] == origin]

    if selected_data.empty:
        return "No data available for the particular origin"

    immigrant_years = selected_data.columns[7:]

    selected_data[immigrant_years] = selected_data[immigrant_years].apply(pd.to_numeric, errors='coerce')

    max_immigrant_year = selected_data[immigrant_years].idxmax(axis=1).iloc[0]

    return max_immigrant_year

result1 = max_immigrant_year('Afghanistan')
result2 = max_immigrant_year('Brazil')
print("Year with the maximum immigrants:")
print(result1)
print(result2)

Year with the maximum immigrants:
2001
2010

In [36]:
# sample code to test your answer
# max_year ("Afghanistan")
# output: 2001

## Question 5  ( 15 pts)
Write a function named **match_name** which searches a specified pattern in the values of **OdName** and returns all the matched records.

For example, set **'Austr'** as the parameter, this function will return the dataframe with the records of both **Austrialia** and **Austria**.

In [37]:
def match_name(pattern):
    records = df[df['OdName'].str.contains(pattern, case=False)]
    return records

matched_df = match_name('Austr')
print(matched_df)

          Type    Coverage     OdName  AREA AreaName  REG  \
9   Immigrants  Foreigners  Australia   909  Oceania  927
10  Immigrants  Foreigners    Austria   908   Europe  926

                      RegName  DEV            DevName  1980  ...  2004  2005  \
9   Australia and New Zealand  901  Developed regions   702  ...   930   909
10             Western Europe  901  Developed regions   234  ...   118   122

    2006  2007  2008  2009  2010  2011  2012  2013
9    875  1033  1018  1018   933   851   982  1121
10   102    98    91   109   124    84   102    90

[2 rows x 43 columns]

In [38]:
# sample code to test your answer
# match_name('Austr')
# There should be two records of both Australia and Austra

In [39]:
matched_df = match_name('Ban')
print(matched_df)

          Type    Coverage      OdName  AREA AreaName   REG          RegName  \
1   Immigrants  Foreigners     Albania   908   Europe   925  Southern Europe
14  Immigrants  Foreigners  Bangladesh   935     Asia  5501    Southern Asia
96  Immigrants  Foreigners     Lebanon   935     Asia   922     Western Asia

    DEV             DevName  1980  ...  2004  2005  2006  2007  2008  2009  \
1   901   Developed regions     1  ...  1450  1223   856   702   560   716
14  902  Developing regions    83  ...  2660  4171  4014  2897  2939  2104
96  902  Developing regions  1409  ...  3293  3709  3802  3467  3566  3077

    2010  2011  2012  2013
1    561   539   620   603
14  4721  2694  2640  3789
96  3432  3072  1614  2172

[3 rows x 43 columns]